[package]
name = "GetSmtcInfo"
version = "0.1.0"
edition = "2021"


[dependencies.windows]
version = "0.58.0"
features = ["Media_Control", "Foundation"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
